name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Restore .env for backend
        run: /home/etrakselis/restore_backend_env.sh  

      - name: Build or deploy
        run: |
          cd $GITHUB_WORKSPACE         
          git status

      - name: Install backend dependencies for app.js
        run: |
          cd backend
          npm install

      - name: Install backend dependencies for nbaRanking.js
        run: |
          cd NBA_RANKING_API
          npm install     

      - name: Restart app.js
        run: |
          cd backend
          pm2 restart node-api || pm2 start app.js --name node-api --watch

      - name: Restart nbaRanking.js
        run: |
          cd NBA_RANKING_API
          pm2 restart nba-ranking-api || pm2 start nbaRanking.js --name nba-ranking-api --watch     
