name: 🚀 Deploy via Self-Hosted Runner

on:
  push:
    branches: [main]  # or your deploy branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull & Restart App
        run: |
          cd /home/etrakselis
          git pull origin main
