name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Build or deploy
        run: |
          cd $GITHUB_WORKSPACE         
          git status

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Restart node
        run: |
          cd backend
          pm2 restart node-api || pm2 start app.js --name node-api --watch
